### ISSUE TITLE
getBlockOfRows can not return  block of rows exceeding 2 gigabytes

### ISSUE THREAD

**Issue by xwu99** [oneapi-src/oneDAL#1476]
We used oneDAL API for NumericTable backed by ByteBuffer, output the following message:

java.lang.IllegalArgumentException: size of the block of rows cannot exceed 2 gigabytes
  at com.intel.daal.data_management.data.HomogenNumericTableByteBufferImpl.getBlockOfRows(Unknown Source)
  at com.intel.daal.data_management.data.HomogenNumericTable.getBlockOfRows(Unknown Source)\

I checked the code: 

private static final long maxBufferSize = 2147483647; 
long bufferSize = vectorNum * nColumns;
 // Gets data from C++ NumericTable object
if (bufferSize * 4> maxBufferSize) {
    throw new IllegalArgumentException("size of the block of rows cannot exceed 2 gigabytes");
} 

Is it possible to make the maxBufferSize configurable?

**Comment by xwu99** [comment]
@PIVOVAR3AL
